In [59]:
import pandas as pd
import numpy as np
data = pd.read_csv('GSAF5.csv', encoding='ISO-8859-1')

In [2]:
data.head(20)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN
5,2016.09.15.R,15-Sep-16,2016,Boat,AUSTRALIA,Western Australia,Bunbury,Fishing,Occupant: Ben Stratton,NaN,...,NaN,"West Australian, 9/15/2016",2016.09.15.R-boat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.15.R,2016.09.15.R,5988,NaN,NaN
6,2016.09.11,11-Sep-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,male,M,...,3' to 4' shark,"News4Jax, 9/11/2016",2016.09.11-PonteVedra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.11,2016.09.11,5987,NaN,NaN
7,2016.09.07,07-Sep-16,2016,Unprovoked,USA,Hawaii,"Makaha, Oahu",Swimming,female,F,...,"Tiger shark, 10?","Hawaii News Now, 9/7/2016",2016.09.07-Oahu.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.07,2016.09.07,5986,NaN,NaN
8,2016.09.06,06-Sep-16,2016,Unprovoked,NEW CALEDONIA,North Province,Koumac,Kite surfing,David Jewell,M,...,NaN,"TVANouvelles, 9/6/2016",2016.09.06-Jewell.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.06,2016.09.06,5985,NaN,NaN
9,2016.09.05.b,05-Sep-16,2016,Unprovoked,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",Boogie boarding,Rylie Williams,F,...,NaN,"C. Creswell, GSAF",2016.09.05.b-Williams.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.05.b,2016.09.05.b,5984,NaN,NaN
10,2016.09.05.a,05-Sep-16,2016,Unprovoked,AUSTRALIA,Western Australia,Injidup,Surfing,Fraser Penman,M,...,NaN,"Perth Now, 9/5/2016",2016.09.05.a-Penman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.05.a,2016.09.05.a,5983,NaN,NaN
11,2016.09.04,04-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Body boarding,Austin Moore,M,...,NaN,"Orlando Sentinel, 9/7/2016",2016.09.04-Moore.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.04,2016.09.04,5982,NaN,NaN
12,2016.09.01,01-Sep-16,2016,Unprovoked,USA,California,"Refugio State Beach, Santa Barbara County",Spearfishing,Tyler McQuillen,M,...,White shark,"R. Collier, GSAF",2016.09.01-McQuillen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.01,2016.09.01,5981,NaN,NaN
13,2016.08.29.b,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Sam Cumiskey,M,...,"Bull shark, 6'","News Channel 8, 8/30/16",2016.08.29.b-Cumiskey.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.29.b,2016.08.29.b,5980,NaN,NaN
14,2016.08.29.a,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"News Channel 8, 8/30/16",2016.08.29.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.29.a,2016.08.29.a,5979,NaN,NaN
15,2016.08.27,27-Aug-16,2016,Unprovoked,REUNION,NaN,Boucan Canot,Surfing,Laurent Chardard,M,...,"Bull shark, 3.5 m","LaDepeche, 8/29/2016",2016.08.27-Chardard.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.27,2016.08.27,5978,NaN,NaN
16,2016.08.25,25-Aug-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,David Cassetty,M,...,NaN,"First Coast News, 7/25/2016",2016.08.25-Cassetty.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.25,2016.08.25,5977,NaN,NaN
17,2016.08.07,07-Aug-16,2016,Unprovoked,BAHAMAS,New Providence Island,Nassau,Snorkeling,Johnny Stoch,M,...,NaN,"ABC, 8/11/2016",2016.08.07-Stoch.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.07,2016.08.07,5976,NaN,NaN
18,2016.08.06,06-Aug-16,2016,Unprovoked,USA,Hawaii,Maui,SUP Foil boarding,Connor Baxter,M,...,"Tiger shark, 10'","SUP, 8/9/2015",2016.08.06-Baxter.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.06,2016.08.06,5975,NaN,NaN
19,2016.08.04,04-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Nolan Tyler,M,...,Blacktip shark,"News 965, 8/5/2016",2016.06.04-Tyler.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.04,2016.08.04,5974,NaN,NaN

In [3]:
data.columns

Index([u'Case Number', u'Date', u'Year', u'Type', u'Country', u'Area',
       u'Location', u'Activity', u'Name', u'Sex ', u'Age', u'Injury',
       u'Fatal (Y/N)', u'Time', u'Species ', u'Investigator or Source', u'pdf',
       u'href formula', u'href', u'Case Number.1', u'Case Number.2',
       u'original order', u'Unnamed: 22', u'Unnamed: 23'],
      dtype='object')

In [4]:
# saco los valores nulos por columnas, y que me muestre las columnas que tienen datos nulos:
null_cols = data.isnull().sum()
null_cols[null_cols > 0]

Country                     43
Area                       402
Location                   496
Activity                   527
Name                       200
Sex                        567
Age                       2681
Injury                      27
Fatal (Y/N)                 19
Time                      3213
Species                   2934
Investigator or Source      15
href formula                 1
href                         3
Unnamed: 22               5991
Unnamed: 23               5990
dtype: int64

In [5]:
#elimino las columnas que tienen mas de 5000 valores nulos:
drop_cols = list(null_cols[null_cols > 5000].index)
drop_cols

['Unnamed: 22', 'Unnamed: 23']

In [6]:
data.columns

Index([u'Case Number', u'Date', u'Year', u'Type', u'Country', u'Area',
       u'Location', u'Activity', u'Name', u'Sex ', u'Age', u'Injury',
       u'Fatal (Y/N)', u'Time', u'Species ', u'Investigator or Source', u'pdf',
       u'href formula', u'href', u'Case Number.1', u'Case Number.2',
       u'original order', u'Unnamed: 22', u'Unnamed: 23'],
      dtype='object')

In [7]:
#muestro el DataFrame sin las columnas que tenian mas de 5000 valores nulos:
data_without_nulls = data.drop(drop_cols, axis=1)
data_without_nulls.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989

In [8]:
data_without_nulls.columns

Index([u'Case Number', u'Date', u'Year', u'Type', u'Country', u'Area',
       u'Location', u'Activity', u'Name', u'Sex ', u'Age', u'Injury',
       u'Fatal (Y/N)', u'Time', u'Species ', u'Investigator or Source', u'pdf',
       u'href formula', u'href', u'Case Number.1', u'Case Number.2',
       u'original order'],
      dtype='object')

In [9]:
#elimino las columnas que no me interesan:
col_lst = ['pdf', 'href formula', 'href', 'Case Number.1', 'Case Number.2', 'Name']
data_clean1 = data_without_nulls.drop(col_lst, axis=1, inplace=False)

data_clean1.columns

Index([u'Case Number', u'Date', u'Year', u'Type', u'Country', u'Area',
       u'Location', u'Activity', u'Sex ', u'Age', u'Injury', u'Fatal (Y/N)',
       u'Time', u'Species ', u'Investigator or Source', u'original order'],
      dtype='object')

In [10]:
#reorganizamos las columnas para que se puedan interpretar mejor:
column_order = ['Year', 'Date', 'Time','Country', 'Area', 'Location', 'Activity','Type', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Species ','Case Number', 'original order']

data_clean1 = data_clean1[column_order]
data_clean1.head(10)

,Year,Date,Time,Country,Area,Location,Activity,Type,Sex,Age,Injury,Fatal (Y/N),Species,Case Number,original order
0,2016,18-Sep-16,13h00,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Unprovoked,M,16,Minor injury to thigh,N,NaN,2016.09.18.c,5993
1,2016,18-Sep-16,11h00,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Unprovoked,M,36,Lacerations to hands,N,NaN,2016.09.18.b,5992
2,2016,18-Sep-16,10h43,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Unprovoked,M,43,Lacerations to lower leg,N,NaN,2016.09.18.a,5991
3,2016,17-Sep-16,NaN,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Unprovoked,M,NaN,Struck by fin on chest & leg,N,NaN,2016.09.17,5990
4,2016,16-Sep-16,NaN,AUSTRALIA,Victoria,Bells Beach,Surfing,Unprovoked,M,NaN,No injury: Knocked off board by shark,N,2 m shark,2016.09.15,5989
5,2016,15-Sep-16,NaN,AUSTRALIA,Western Australia,Bunbury,Fishing,Boat,NaN,NaN,Shark rammed boat. No injury to occupant,N,NaN,2016.09.15.R,5988
6,2016,11-Sep-16,15h15,USA,Florida,"Ponte Vedra, St. Johns County",Wading,Unprovoked,M,60s,Minor injury to arm,N,3' to 4' shark,2016.09.11,5987
7,2016,07-Sep-16,14h30,USA,Hawaii,"Makaha, Oahu",Swimming,Unprovoked,F,51,Severe lacerations to shoulder & forearm,N,"Tiger shark, 10?",2016.09.07,5986
8,2016,06-Sep-16,15h40,NEW CALEDONIA,North Province,Koumac,Kite surfing,Unprovoked,M,50,FATAL,Y,NaN,2016.09.06,5985
9,2016,05-Sep-16,Late afternoon,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",Boogie boarding,Unprovoked,F,12,Lacerations & punctures to lower right leg,N,NaN,2016.09.05.b,5984

In [11]:
#analizo los datos de la columna "year" para ver que datos muestra:
print(set(data_clean1['Year']))

set([0, 5, 1543, 1554, 1555, 1580, 1595, 77, 1617, 1637, 1638, 1642, 1700, 1703, 1721, 1733, 1738, 1742, 1748, 1749, 1755, 1758, 1764, 1767, 1771, 1776, 1779, 1785, 1787, 1788, 1791, 1800, 1803, 1804, 1805, 1807, 1811, 1812, 1816, 1817, 1818, 1819, 1822, 1825, 1826, 1827, 1828, 1829, 1830, 1831, 1832, 1834, 1835, 1836, 1837, 1839, 1840, 1841, 1842, 1844, 1845, 1846, 1847, 1848, 1849, 1850, 1851, 1852, 1853, 1854, 1855, 1856, 1858, 1859, 1860, 1861, 1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 500])

In [12]:
#elimino los registros anteriores al año 1600, porque no considero que la informacion sea veraz:
data_clean2 = data_clean1.drop(data_clean1[data_clean1['Year']< 1600].index, axis=0, inplace = False)
data_clean2

,Year,Date,Time,Country,Area,Location,Activity,Type,Sex,Age,Injury,Fatal (Y/N),Species,Case Number,original order
0,2016,18-Sep-16,13h00,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Unprovoked,M,16,Minor injury to thigh,N,NaN,2016.09.18.c,5993
1,2016,18-Sep-16,11h00,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Unprovoked,M,36,Lacerations to hands,N,NaN,2016.09.18.b,5992
2,2016,18-Sep-16,10h43,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Unprovoked,M,43,Lacerations to lower leg,N,NaN,2016.09.18.a,5991
3,2016,17-Sep-16,NaN,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Unprovoked,M,NaN,Struck by fin on chest & leg,N,NaN,2016.09.17,5990
4,2016,16-Sep-16,NaN,AUSTRALIA,Victoria,Bells Beach,Surfing,Unprovoked,M,NaN,No injury: Knocked off board by shark,N,2 m shark,2016.09.15,5989
5,2016,15-Sep-16,NaN,AUSTRALIA,Western Australia,Bunbury,Fishing,Boat,NaN,NaN,Shark rammed boat. No injury to occupant,N,NaN,2016.09.15.R,5988
6,2016,11-Sep-16,15h15,USA,Florida,"Ponte Vedra, St. Johns County",Wading,Unprovoked,M,60s,Minor injury to arm,N,3' to 4' shark,2016.09.11,5987
7,2016,07-Sep-16,14h30,USA,Hawaii,"Makaha, Oahu",Swimming,Unprovoked,F,51,Severe lacerations to shoulder & forearm,N,"Tiger shark, 10?",2016.09.07,5986
8,2016,06-Sep-16,15h40,NEW CALEDONIA,North Province,Koumac,Kite surfing,Unprovoked,M,50,FATAL,Y,NaN,2016.09.06,5985
9,2016,05-Sep-16,Late afternoon,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",Boogie boarding,Unprovoked,F,12,Lacerations & punctures to lower right leg,N,NaN,2016.09.05.b,5984
10,2016,05-Sep-16,Late afternoon,AUSTRALIA,Western Australia,Injidup,Surfing,Unprovoked,M,NaN,"No inury, board broken in half by shark",N,NaN,2016.09.05.a,5983
11,2016,04-Sep-16,NaN,USA,Florida,"New Smyrna Beach, Volusia County",Body boarding,Unprovoked,M,9,Foot bitten,N,NaN,2016.09.04,5982
12,2016,01-Sep-16,NaN,USA,California,"Refugio State Beach, Santa Barbara County",Spearfishing,Unprovoked,M,22,Two toes broken & lacerated,N,White shark,2016.09.01,5981
13,2016,29-Aug-16,15h00,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Unprovoked,M,25,Lacerations to right foot,N,"Bull shark, 6'",2016.08.29.b,5980
14,2016,29-Aug-16,14h00,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Unprovoked,M,37,Minor injury to ankle,N,NaN,2016.08.29.a,5979
15,2016,27-Aug-16,17h00,REUNION,NaN,Boucan Canot,Surfing,Unprovoked,M,20,"Right arm severed, ankle severely bitten",N,"Bull shark, 3.5 m",2016.08.27,5978
16,2016,25-Aug-16,16h00,USA,Florida,"Ponte Vedra, St. Johns County",Wading,Unprovoked,M,49,Minor injury to ankle,N,NaN,2016.08.25,5977
17,2016,07-Aug-16,NaN,BAHAMAS,New Providence Island,Nassau,Snorkeling,Unprovoked,M,15,Lacerations to left leg,N,NaN,2016.08.07,5976
18,2016,06-Aug-16,NaN,USA,Hawaii,Maui,SUP Foil boarding,Unprovoked,M,21,"No inury, shark & board collided",N,"Tiger shark, 10'",2016.08.06,5975
19,2016,04-Aug-16,NaN,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Unprovoked,M,22,Big toe bitten,N,Blacktip shark,2016.08.04,5974
20,2016,29-Jul-16,11h30,SPAIN,Alicante Province,Arenales del Sol,Swimming,Unprovoked,M,40,Lacerations to right hand,N,Blue shark,2016.07.29,5973
21,2016,28-Jul-16,NaN,CHINA,Hong Kong,NaN,Swimming,Unprovoked,M,72,Lacerations to leg,N,NaN,2016.07.28.R,5972
22,2016,28-Jul-16,NaN,AUSTRALIA,Western Australia,Near Albany,Kayaking,Boat,M,NaN,"No injury, shark nudged kayak repeatedly",N,White shark,2016.07.28,5971
23,2016,27-Jul-16,NaN,USA,Florida,"Florida Keys, Monroe County",Lobstering,Provoked,M,43,Laceration to left forearm PROVOKED INCIDENT,N,"Nurse shark, 4'",2016.07.27,5970
24,2016,26-Jul-16,12h00,AUSTRALIA,New South Wales,"Sharpes Beach, Ballina",Surfing,Unprovoked,M,18,"No injury. Leg rope severed, knocked off board...",N,NaN,2016.07.26,5969
25,2016,24-Jul-16,19h05,JAPAN,Kochi Prefecture,Irino Beach,Surfing,Unprovoked,M,29,Lacerations to left leg,N,NaN,2016.07.24,5968
26,2016,23-Jul-16,NaN,AUSTRALIA,Tasmania,Clifton Beach,Surfing,Unprovoked,M,36,Calf bumped but no injury,N,NaN,2016.07.23.b,5967
27,2016,23-Jul-16,NaN,BAHAMAS,Abaco Islands,Green Turtle Cay,Spearfishing,Unprovoked,M,NaN,Lacerations to face and right leg,N,"Bull shark, 6'",2016.07.23.a,5966
28,2016,20-Jul-16,After noon,AUSTRALIA,Queensland,"20 k off The Spit, off the Gold Coast",Fishing,Provoked,M,31,Laceration to left calf from hooked shark PROV...,N,"reef shark, 1m",2016.07.20,5965
29,2016,17-Jul-16,NaN,USA,Alabama,8 miles off Mobile,Fishing in Alabama Deep Fishing Rodeo,Boat,NaN,NaN,"No injury, shark bit trolling motor",N,"Tiger shark, 10'",2016.07.17,5964
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5830,1804,Reported 26-Feb-1804,NaN,AUSTRALIA,New South Wales,"Georges Head, off Port Jackson",NaN,Boat,NaN,NaN,No injury to occupants,N,NaN,1804.02.26.R,163
5831,1803,Mar-1803,NaN,AUSTRALIA,Western Australia,"Hamelin Harbour, at Faure Island",NaN,Unprovoked,M,NaN,Shark knocked him down & tore clothing of the ...,N,NaN,1803.03.00,162
5832,1800,1800,NaN,SEYCHELLES,St. Anne,NaN,a corsair's boat was overturned,Unprovoked,F,NaN,"FATAL, all onboard were killed by sharks",Y,NaN,1800.00.00,161
5833,1791,1791,NaN,AUSTRALIA,New South Wales,Port Jackson,NaN,Unprovoked,F,NaN,"FATAL, ""bitten in two""",Y,NaN,1791.00.00,160
5834,1788,10-May-1788,NaN,AUSTRALIA,New South Wales,Sydney Harbor,Fishing,Boat,NaN,NaN,"No injury to occupants, shark bit oar and rudder",N,NaN,1788.05.10,159
5835,1787,05-Jul-1787,NaN,St Helena,NaN,Landing Place,Swimming,Unprovoked,M,NaN,FATAL,Y,NaN,1787.07.05,158
5836,1785,Reported 26-Sep-1785,NaN,ENGLAND,Sussex,Brighton,NaN,Unprovoked,M,NaN,Human remains recovered from shark,Y,Tiger shark?,1785.09.26.R,157
5837,1779,1779,NaN,USA,Hawaii,"Maliu, Hawai'i",Surfing,Unprovoked,M,young,"FATAL, buttock lacerated",Y,NaN,1779.00.00,156
5838,1776,Reported 1776,NaN,GUINEA,NaN,NaN,Murder,Unprovoked,M,NaN,FATAL,Y,NaN,1776.00.00.R,155
5839,1776,1776,NaN,GREENLAND,NaN,NaN,NaN,Boat,NaN,NaN,FATAL,Y,White sharks,1776.00.00.b,154
5840,1771,Reported 12-Jul-1771,NaN,USA,NaN,Damiscotte,Fishing,Unprovoked,M,NaN,FATAL,Y,NaN,1771.07.12.R,153
5841,1767,1767,NaN,FRANCE,C�te d'Azur,St. Tropez,Bathing,Invalid,M,NaN,Lacerations to arm & leg,N,Description of shark does not ring true,1767.00.00,152
5842,1764,1764,NaN,SPAIN,NaN,Guadalquivir River,Swimming,Unprovoked,M,NaN,FATAL,Y,NaN,1764.00.00,151
5843,1758,1758,NaN,MEDITERRANEAN SEA,NaN,NaN,Fell overboard from a frigate & was swallowed ...,Unprovoked,M,NaN,"""He was taken up alive and but little injured.""",N,"""The fish was harpooned, dried, and presented ...",1758.00.00,150
5844,1749,1749,NaN,CUBA,Havana Province,Havana Harbor,Swimming,Unprovoked,M,14,Right leg severed at knee. In 1796 he became ...,N,NaN,1749.00.00,149
5845,1755,1755,NaN,SWEDEN,Skagerrak arm of the North Sea,Bohusl�n,NaN,Unprovoked,M,NaN,NaN,UNKNOWN,NaN,1755.00.00,148
5846,1748,1748,NaN,PANAMA,Las Perlas archipelago,Taboga & Isla del Rey,Pearl diving,Unprovoked,M,NaN,FATAL,Y,NaN,1748.00.00,147
5847,1742,17-Dec-1742,NaN,NaN,NaN,Carlisle Bay,Swimming,Unprovoked,M,NaN,FATAL,Y,NaN,1742.12.17,146
5848,1738,Reported 06-Apr-1738,NaN,ITALY,Sicily,Strait of Messina,Swimming,Unprovoked,M,NaN,FATAL,Y,NaN,1738.04.06.R,145
5849,1733,1733,NaN,ICELAND,Bardestrand,Talkknefiord,NaN,Invalid,NaN,NaN,"Partial hominid remains recovered from shark, ...",NaN,NaN,1733.00.00,144
5850,1721,June 1721,NaN,ITALY,Sardinia,"Ponte della Maddelena,",Swimming,Unprovoked,M,NaN,"FATAL, partial remains recovered from shark�s...",Y,"White shark, 1600-lb female",1721.06.00,143
5851,1703,26-Mar-1703,Night,BARBADOS,Southwest coast,Carlisle Bay,Swimming,Unprovoked,M,19,"Hand and foot severely bitten, surgically ampu...",N,NaN,1703.03.26,142
5852,1700,1700s,NaN,FRANCE,NaN,Nice,NaN,Unprovoked,M,NaN,FATAL,Y,NaN,1700.00.00.c,141
5853,1700,1700s,NaN,FRANCE,C�te d'Azur,Antibes,Bathing,Unprovoked,M,NaN,Leg severed,N,White shark,1700.00.00.b,140
5854,1700,1700s,NaN,BARBADOS,NaN,NaN,Bathing,Unprovoked,M,NaN,FATAL,Y,NaN,1700.00.00.a,139
5855,1642,Late 1600s Reported 1728,NaN,GUINEA,NaN,NaN,Went overboard,Invalid,M,NaN,FATAL,Y,NaN,1642.00.00.b,138
5856,1638,Reported 1638,NaN,NaN,NaN,NaN,NaN,Unprovoked,M,NaN,NaN,UNKNOWN,NaN,1638.00.00.R,137
5857,1637,Reported 1637,NaN,INDIA,West Bengal,Hooghly River mouth,Wading,Unprovoked,NaN,NaN,NaN,UNKNOWN,NaN,1637.00.00.R,136
5858,1617,Reported 1617,NaN,INDIA,West Bengal,Ganges Delta,NaN,Unprovoked,NaN,NaN,NaN,UNKNOWN,NaN,1617.00.00.R,135
5859,1642,1642,NaN,USA,New York,Between Manhattan and The Bronx,Swimming,Unprovoked,M,NaN,FATAL,Y,NaN,1642.00.00,134

In [13]:
print(set(data_clean2['Fatal (Y/N)']))

set([nan, 'F', 'N ', 'UNKNOWN', ' N', 'N', '#VALUE!', 'Y', 'n'])

In [44]:
#homogeneizamos los datos de la columna Fatal (Y/N):
data_clean2['Fatal (Y/N)'] = data_clean2['Fatal (Y/N)'].str.replace('n', 'N')
data_clean2['Fatal (Y/N)'] = data_clean2['Fatal (Y/N)'].str.replace('F', 'UNKNOWN')
data_clean2['Fatal (Y/N)'] = data_clean2['Fatal (Y/N)'].str.replace('N ', 'N')
data_clean2['Fatal (Y/N)'] = data_clean2['Fatal (Y/N)'].str.replace(' N', 'N')
data_clean2['Fatal (Y/N)'] = data_clean2['Fatal (Y/N)'].str.replace('#VALUE!', 'UNKNOWN')
data_clean2['Fatal (Y/N)'].fillna(value='UNKNOWN', inplace=True)
print(set(data_clean2['Fatal (Y/N)']))

set(['Y', 'UNKNOWN', 'N'])

In [15]:
#incluyo una columna con el numero de accidentes:

data_clean2['N_Attacks'] = data_clean2['original order'].count()/len(data_clean2['original order'])
data_clean2.head(10)

,Year,Date,Time,Country,Area,Location,Activity,Type,Sex,Age,Injury,Fatal (Y/N),Species,Case Number,original order,N_Attacks
0,2016,18-Sep-16,13h00,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Unprovoked,M,16,Minor injury to thigh,N,NaN,2016.09.18.c,5993,1
1,2016,18-Sep-16,11h00,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Unprovoked,M,36,Lacerations to hands,N,NaN,2016.09.18.b,5992,1
2,2016,18-Sep-16,10h43,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Unprovoked,M,43,Lacerations to lower leg,N,NaN,2016.09.18.a,5991,1
3,2016,17-Sep-16,NaN,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Unprovoked,M,NaN,Struck by fin on chest & leg,N,NaN,2016.09.17,5990,1
4,2016,16-Sep-16,NaN,AUSTRALIA,Victoria,Bells Beach,Surfing,Unprovoked,M,NaN,No injury: Knocked off board by shark,N,2 m shark,2016.09.15,5989,1
5,2016,15-Sep-16,NaN,AUSTRALIA,Western Australia,Bunbury,Fishing,Boat,NaN,NaN,Shark rammed boat. No injury to occupant,N,NaN,2016.09.15.R,5988,1
6,2016,11-Sep-16,15h15,USA,Florida,"Ponte Vedra, St. Johns County",Wading,Unprovoked,M,60s,Minor injury to arm,N,3' to 4' shark,2016.09.11,5987,1
7,2016,07-Sep-16,14h30,USA,Hawaii,"Makaha, Oahu",Swimming,Unprovoked,F,51,Severe lacerations to shoulder & forearm,N,"Tiger shark, 10?",2016.09.07,5986,1
8,2016,06-Sep-16,15h40,NEW CALEDONIA,North Province,Koumac,Kite surfing,Unprovoked,M,50,FATAL,Y,NaN,2016.09.06,5985,1
9,2016,05-Sep-16,Late afternoon,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",Boogie boarding,Unprovoked,F,12,Lacerations & punctures to lower right leg,N,NaN,2016.09.05.b,5984,1

In [16]:
#Ordenar por años/pais/area en orden descendente:
final_dataclean = data_clean2.sort_values(by=['Year', 'Country', 'Area'], ascending=False)
final_dataclean

,Year,Date,Time,Country,Area,Location,Activity,Type,Sex,Age,Injury,Fatal (Y/N),Species,Case Number,original order,N_Attacks
48,2016,14-Jun-16,17h30,USA,Texas,"Pirates Beach, Galveston",Floating in tube,Unprovoked,F,6,Injury to lower leg,N,3' to 4' shark,2016.06.14,5945,1
97,2016,24-Jan-16,09h30 / 10h00,USA,Texas,Off Surfside,Spearfishing,Unprovoked,M,NaN,"Bruised ribs & tail bone, speargun broken and ...",N,Bull sharks x 2,2016.01.24.b,5896,1
9,2016,05-Sep-16,Late afternoon,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",Boogie boarding,Unprovoked,F,12,Lacerations & punctures to lower right leg,N,NaN,2016.09.05.b,5984,1
32,2016,15-Jul-16,NaN,USA,South Carolina,"North Myrtle Beach, Horry County",Swimming,Unprovoked,M,NaN,Puncture wounds to foot,N,NaN,2016.07.15,5961,1
40,2016,27-Jun-16,16h20,USA,South Carolina,Sullivan's Island,NaN,Unprovoked,M,35,Minor injury,N,3' to 4' shark,2016.06.27,5953,1
44,2016,21-Jun-16,15h25,USA,South Carolina,"North Myrtle Beach, Horry County",Floating,Unprovoked,M,42,Lacerations and punctures to foot,N,3' to 5' shark,2016.06.21.b,5949,1
50,2016,07-Jun-16,11h30,USA,South Carolina,"Folly Beach, Charleston County",Surfing,Invalid,M,27,"No injury, board damaged",N,Said to involve an 8' shark but more likely da...,2016.06.07,5943,1
41,2016,25-Jun-16,14h34,USA,North Carolina,"Atlantic Beach, Emerald Isle, Carteret County",Surfing,Unprovoked,M,11,Foot injured,N,NaN,2016.06.25,5952,1
49,2016,11-Jun-16,15h00,USA,North Carolina,"Atlantic Beach, Emerald Isle, Carteret County",Standing,Unprovoked,M,19,Laceration to wrist,N,3' shark,2016.06.11,5944,1
36,2016,07-Jul-16,10h00,USA,Massachusetts,"Off Gloucester, Essec County",Fishing,Provoked,M,59,Fin of hooked shark injured fisherman's forear...,N,dogfish shark,2016.07.07.b,5957,1
7,2016,07-Sep-16,14h30,USA,Hawaii,"Makaha, Oahu",Swimming,Unprovoked,F,51,Severe lacerations to shoulder & forearm,N,"Tiger shark, 10?",2016.09.07,5986,1
18,2016,06-Aug-16,NaN,USA,Hawaii,Maui,SUP Foil boarding,Unprovoked,M,21,"No inury, shark & board collided",N,"Tiger shark, 10'",2016.08.06,5975,1
46,2016,15-Jun-16,06h00,USA,Hawaii,"Kalapaki Beach, Kauai",Surfing,Unprovoked,M,NaN,Single puncture wound to arm,N,3' to 4' shark,2016.06.15.b,5947,1
64,2016,03-May-16,15h49,USA,Hawaii,"Wailea Beach, Maui",Floating,Unprovoked,M,59,Minor lacerations to right shoulder,N,NaN,2016.05.03,5929,1
76,2016,31-Mar-16,11h00,USA,Hawaii,"Olowalu, Maui",Snorkeling,Unprovoked,F,46,Minor injury to left foot,N,NaN,2016.03.31,5917,1
95,2016,28-Jan-16,14h00,USA,Hawaii,"Hanalei Bay, Kauai",Surfing,Unprovoked,M,NaN,Lacerations to both hands,N,"Reef shark, 5'",2016.01.28,5898,1
96,2016,25-Jan-16,11h30,USA,Hawaii,"Hanalei Bay, Kauai,",Surfing,Unprovoked,F,15,No injury,N,NaN,2016.01.25,5897,1
99,2016,23-Jan-16,Morning,USA,Hawaii,"Wailea Beach, Maui",Paddle boarding,Unprovoked,M,48,No injury,N,"Tiger shark, 14'",2016.01.23,5894,1
0,2016,18-Sep-16,13h00,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Unprovoked,M,16,Minor injury to thigh,N,NaN,2016.09.18.c,5993,1
1,2016,18-Sep-16,11h00,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Unprovoked,M,36,Lacerations to hands,N,NaN,2016.09.18.b,5992,1
2,2016,18-Sep-16,10h43,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Unprovoked,M,43,Lacerations to lower leg,N,NaN,2016.09.18.a,5991,1
6,2016,11-Sep-16,15h15,USA,Florida,"Ponte Vedra, St. Johns County",Wading,Unprovoked,M,60s,Minor injury to arm,N,3' to 4' shark,2016.09.11,5987,1
11,2016,04-Sep-16,NaN,USA,Florida,"New Smyrna Beach, Volusia County",Body boarding,Unprovoked,M,9,Foot bitten,N,NaN,2016.09.04,5982,1
13,2016,29-Aug-16,15h00,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Unprovoked,M,25,Lacerations to right foot,N,"Bull shark, 6'",2016.08.29.b,5980,1
14,2016,29-Aug-16,14h00,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Unprovoked,M,37,Minor injury to ankle,N,NaN,2016.08.29.a,5979,1
16,2016,25-Aug-16,16h00,USA,Florida,"Ponte Vedra, St. Johns County",Wading,Unprovoked,M,49,Minor injury to ankle,N,NaN,2016.08.25,5977,1
19,2016,04-Aug-16,NaN,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Unprovoked,M,22,Big toe bitten,N,Blacktip shark,2016.08.04,5974,1
23,2016,27-Jul-16,NaN,USA,Florida,"Florida Keys, Monroe County",Lobstering,Provoked,M,43,Laceration to left forearm PROVOKED INCIDENT,N,"Nurse shark, 4'",2016.07.27,5970,1
30,2016,16-Jul-16,1300,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Unprovoked,F,9,Minor injury to leg,N,NaN,2016.07.16.b,5963,1
31,2016,16-Jul-16,11h00,USA,Florida,"New Smyrna Beach, Volusia County",NaN,Unprovoked,F,11,Minor injury to toes,N,NaN,2016.07.16.a,5962,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5830,1804,Reported 26-Feb-1804,NaN,AUSTRALIA,New South Wales,"Georges Head, off Port Jackson",NaN,Boat,NaN,NaN,No injury to occupants,N,NaN,1804.02.26.R,163,1
5831,1803,Mar-1803,NaN,AUSTRALIA,Western Australia,"Hamelin Harbour, at Faure Island",NaN,Unprovoked,M,NaN,Shark knocked him down & tore clothing of the ...,N,NaN,1803.03.00,162,1
5832,1800,1800,NaN,SEYCHELLES,St. Anne,NaN,a corsair's boat was overturned,Unprovoked,F,NaN,"FATAL, all onboard were killed by sharks",Y,NaN,1800.00.00,161,1
5833,1791,1791,NaN,AUSTRALIA,New South Wales,Port Jackson,NaN,Unprovoked,F,NaN,"FATAL, ""bitten in two""",Y,NaN,1791.00.00,160,1
5834,1788,10-May-1788,NaN,AUSTRALIA,New South Wales,Sydney Harbor,Fishing,Boat,NaN,NaN,"No injury to occupants, shark bit oar and rudder",N,NaN,1788.05.10,159,1
5835,1787,05-Jul-1787,NaN,St Helena,NaN,Landing Place,Swimming,Unprovoked,M,NaN,FATAL,Y,NaN,1787.07.05,158,1
5836,1785,Reported 26-Sep-1785,NaN,ENGLAND,Sussex,Brighton,NaN,Unprovoked,M,NaN,Human remains recovered from shark,Y,Tiger shark?,1785.09.26.R,157,1
5837,1779,1779,NaN,USA,Hawaii,"Maliu, Hawai'i",Surfing,Unprovoked,M,young,"FATAL, buttock lacerated",Y,NaN,1779.00.00,156,1
5838,1776,Reported 1776,NaN,GUINEA,NaN,NaN,Murder,Unprovoked,M,NaN,FATAL,Y,NaN,1776.00.00.R,155,1
5839,1776,1776,NaN,GREENLAND,NaN,NaN,NaN,Boat,NaN,NaN,FATAL,Y,White sharks,1776.00.00.b,154,1
5840,1771,Reported 12-Jul-1771,NaN,USA,NaN,Damiscotte,Fishing,Unprovoked,M,NaN,FATAL,Y,NaN,1771.07.12.R,153,1
5841,1767,1767,NaN,FRANCE,C�te d'Azur,St. Tropez,Bathing,Invalid,M,NaN,Lacerations to arm & leg,N,Description of shark does not ring true,1767.00.00,152,1
5842,1764,1764,NaN,SPAIN,NaN,Guadalquivir River,Swimming,Unprovoked,M,NaN,FATAL,Y,NaN,1764.00.00,151,1
5843,1758,1758,NaN,MEDITERRANEAN SEA,NaN,NaN,Fell overboard from a frigate & was swallowed ...,Unprovoked,M,NaN,"""He was taken up alive and but little injured.""",N,"""The fish was harpooned, dried, and presented ...",1758.00.00,150,1
5845,1755,1755,NaN,SWEDEN,Skagerrak arm of the North Sea,Bohusl�n,NaN,Unprovoked,M,NaN,NaN,UNKNOWN,NaN,1755.00.00,148,1
5844,1749,1749,NaN,CUBA,Havana Province,Havana Harbor,Swimming,Unprovoked,M,14,Right leg severed at knee. In 1796 he became ...,N,NaN,1749.00.00,149,1
5846,1748,1748,NaN,PANAMA,Las Perlas archipelago,Taboga & Isla del Rey,Pearl diving,Unprovoked,M,NaN,FATAL,Y,NaN,1748.00.00,147,1
5847,1742,17-Dec-1742,NaN,NaN,NaN,Carlisle Bay,Swimming,Unprovoked,M,NaN,FATAL,Y,NaN,1742.12.17,146,1
5848,1738,Reported 06-Apr-1738,NaN,ITALY,Sicily,Strait of Messina,Swimming,Unprovoked,M,NaN,FATAL,Y,NaN,1738.04.06.R,145,1
5849,1733,1733,NaN,ICELAND,Bardestrand,Talkknefiord,NaN,Invalid,NaN,NaN,"Partial hominid remains recovered from shark, ...",UNKNOWN,NaN,1733.00.00,144,1
5850,1721,June 1721,NaN,ITALY,Sardinia,"Ponte della Maddelena,",Swimming,Unprovoked,M,NaN,"FATAL, partial remains recovered from shark�s...",Y,"White shark, 1600-lb female",1721.06.00,143,1
5851,1703,26-Mar-1703,Night,BARBADOS,Southwest coast,Carlisle Bay,Swimming,Unprovoked,M,19,"Hand and foot severely bitten, surgically ampu...",N,NaN,1703.03.26,142,1
5853,1700,1700s,NaN,FRANCE,C�te d'Azur,Antibes,Bathing,Unprovoked,M,NaN,Leg severed,N,White shark,1700.00.00.b,140,1
5852,1700,1700s,NaN,FRANCE,NaN,Nice,NaN,Unprovoked,M,NaN,FATAL,Y,NaN,1700.00.00.c,141,1
5854,1700,1700s,NaN,BARBADOS,NaN,NaN,Bathing,Unprovoked,M,NaN,FATAL,Y,NaN,1700.00.00.a,139,1
5859,1642,1642,NaN,USA,New York,Between Manhattan and The Bronx,Swimming,Unprovoked,M,NaN,FATAL,Y,NaN,1642.00.00,134,1
5855,1642,Late 1600s Reported 1728,NaN,GUINEA,NaN,NaN,Went overboard,Invalid,M,NaN,FATAL,Y,NaN,1642.00.00.b,138,1
5856,1638,Reported 1638,NaN,NaN,NaN,NaN,NaN,Unprovoked,M,NaN,NaN,UNKNOWN,NaN,1638.00.00.R,137,1
5857,1637,Reported 1637,NaN,INDIA,West Bengal,Hooghly River mouth,Wading,Unprovoked,NaN,NaN,NaN,UNKNOWN,NaN,1637.00.00.R,136,1
5858,1617,Reported 1617,NaN,INDIA,West Bengal,Ganges Delta,NaN,Unprovoked,NaN,NaN,NaN,UNKNOWN,NaN,1617.00.00.R,135,1

In [17]:
#calculamos los ataques registrados por paises, ordenado  de mayor a menor:
Attacks_per_Country = data_clean2.groupby(['Country'])['N_Attacks'].sum()
Attacks_per_Country
Attacks_per_Country_ordered = Attacks_per_Country.sort_values(ascending=False)
Attacks_per_Country_ordered.head(10)

Country
USA                 2099
AUSTRALIA           1262
SOUTH AFRICA         557
PAPUA NEW GUINEA     129
NEW ZEALAND          124
BRAZIL               102
BAHAMAS               95
MEXICO                80
ITALY                 69
PHILIPPINES           59
Name: N_Attacks, dtype: int64

In [18]:
#Analizamos el numero de ataques por pais y por año:
SharkAttacks_per_Country_Year = data_clean2.groupby(['Country','Year'])['N_Attacks'].sum()
SharkAttacks_per_Country_Year_ordered = SharkAttacks_per_Country_Year.sort_values(ascending=False)
SharkAttacks_per_Country_Year_ordered

Country        Year
USA            2015    72
               2007    66
               2014    65
               2012    64
               2008    60
               2013    60
               2001    58
               2003    57
               2006    54
               2005    52
               2000    52
               2016    52
               1995    49
               2002    49
               2011    48
               2009    41
               2010    40
               1999    35
               2004    35
AUSTRALIA      2015    30
               2014    29
USA            1997    28
AUSTRALIA      2009    28
USA            1996    27
               1959    27
               1981    27
               1998    26
               1988    26
AUSTRALIA      2012    26
USA            1989    25
                       ..
NEW ZEALAND    1879     1
               1880     1
               1885     1
               1887     1
               1888     1
               1890     1
               1891     1
               1892     1
               1893     1
NEW GUINEA     1948     1
               1944     1
               1940     1
NEW CALEDONIA  1986     1
               1914     1
               1961     1
               1964     1
               1976     1
               1977     1
               1983     1
               1985     1
               1994     1
NEW GUINEA     1878     1
NEW CALEDONIA  1999     1
               2002     1
               2004     1
               2009     1
               2013     1
               2014     1
               2015     1
 PHILIPPINES   1944     1
Name: N_Attacks, Length: 1749, dtype: int64

In [19]:
#Analizamos los casos de fallecimiento en los ataques(en porcentaje):
SharkAttack_result_percentage= (data_clean2.groupby(['Fatal (Y/N)'])['N_Attacks'].sum())/(data_clean2['N_Attacks'].sum())*100
SharkAttack_result_percentage

Fatal (Y/N)
#VALUE!     0.017065
N          72.645051
UNKNOWN     1.877133
Y          25.460751
Name: N_Attacks, dtype: float64

In [41]:
#Guardo la tabla final_dataclean como .csv:

#SharkAttacks_by_year_country = final_dataclean.to_csv('SharkAttacks_ordered_by_year'), encoding='utf-8')
final_dataclean.to_csv('SharkAttacks_ordered_by_year.csv', index = False)
#SharkAttacks_by_year_country = final_dataclean.to_csv('SharkAttacks_ordered_by_year')