In [1]:
# Suicide Rates Overview 1985 to 2016 
# About this file: country, year, sex, age group, count of suicides, population, suicide rate, country-year composite key, HDI for year, gdp_for_year, gdp_per_capita, generation (based on age grouping average).
# https://www.kaggle.com/russellyates88/suicide-rates-overview-1985-to-2016
# HDI (Human Development Index: El índice de desarrollo humano (IDH) es un indicador del desarrollo humano por país, elaborado por el Programa de las Naciones Unidas para el Desarrollo (PNUD). 
#El índice de Desarrollo Humano (IDH) es un indicador sintético de los logros medios obtenidos en las dimensiones fundamentales del desarrollo humano:
#-tener una vida larga y saludable, 
#-adquirir conocimientos y 
#-disfrutar de un nivel de vida digno. 
#El IDH es la media aritmética de los índices normalizados de cada una de las tres dimensiones.
#Gross Domestic Product - GDP 

#1) Importamos la Dataset:

import pandas as pd

data = pd.read_csv("suicide-rates-overview-1985-to-2016.csv")

data

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers
5,Albania,1987,female,75+ years,1,35600,2.81,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
6,Albania,1987,female,35-54 years,6,278800,2.15,Albania1987,NaN,"2,156,624,900",796,Silent
7,Albania,1987,female,25-34 years,4,257200,1.56,Albania1987,NaN,"2,156,624,900",796,Boomers
8,Albania,1987,male,55-74 years,1,137500,0.73,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
9,Albania,1987,female,5-14 years,0,311000,0.00,Albania1987,NaN,"2,156,624,900",796,Generation X
10,Albania,1987,female,55-74 years,0,144600,0.00,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
11,Albania,1987,male,5-14 years,0,338200,0.00,Albania1987,NaN,"2,156,624,900",796,Generation X
12,Albania,1988,female,75+ years,2,36400,5.49,Albania1988,NaN,"2,126,000,000",769,G.I. Generation
13,Albania,1988,male,15-24 years,17,319200,5.33,Albania1988,NaN,"2,126,000,000",769,Generation X
14,Albania,1988,male,75+ years,1,22300,4.48,Albania1988,NaN,"2,126,000,000",769,G.I. Generation
15,Albania,1988,male,35-54 years,14,314100,4.46,Albania1988,NaN,"2,126,000,000",769,Silent
16,Albania,1988,male,55-74 years,4,140200,2.85,Albania1988,NaN,"2,126,000,000",769,G.I. Generation
17,Albania,1988,female,15-24 years,8,295600,2.71,Albania1988,NaN,"2,126,000,000",769,Generation X
18,Albania,1988,female,55-74 years,3,147500,2.03,Albania1988,NaN,"2,126,000,000",769,G.I. Generation
19,Albania,1988,female,25-34 years,5,262400,1.91,Albania1988,NaN,"2,126,000,000",769,Boomers
20,Albania,1988,male,25-34 years,5,279900,1.79,Albania1988,NaN,"2,126,000,000",769,Boomers
21,Albania,1988,female,35-54 years,4,284500,1.41,Albania1988,NaN,"2,126,000,000",769,Silent
22,Albania,1988,female,5-14 years,0,317200,0.00,Albania1988,NaN,"2,126,000,000",769,Generation X
23,Albania,1988,male,5-14 years,0,345000,0.00,Albania1988,NaN,"2,126,000,000",769,Generation X
24,Albania,1989,male,75+ years,2,22500,8.89,Albania1989,NaN,"2,335,124,988",833,G.I. Generation
25,Albania,1989,male,25-34 years,18,283600,6.35,Albania1989,NaN,"2,335,124,988",833,Boomers
26,Albania,1989,male,35-54 years,15,318400,4.71,Albania1989,NaN,"2,335,124,988",833,Silent
27,Albania,1989,male,55-74 years,6,142100,4.22,Albania1989,NaN,"2,335,124,988",833,G.I. Generation
28,Albania,1989,male,15-24 years,12,323500,3.71,Albania1989,NaN,"2,335,124,988",833,Generation X
29,Albania,1989,female,35-54 years,7,288600,2.43,Albania1989,NaN,"2,335,124,988",833,Silent
...,...,...,...,...,...,...,...,...,...,...,...,...
27790,Uzbekistan,2012,female,25-34 years,148,2556673,5.79,Uzbekistan2012,668.0,"51,821,573,338",1964,Millenials
27791,Uzbekistan,2012,female,35-54 years,89,3474788,2.56,Uzbekistan2012,668.0,"51,821,573,338",1964,Generation X
27792,Uzbekistan,2012,male,5-14 years,67,2701361,2.48,Uzbekistan2012,668.0,"51,821,573,338",1964,Generation Z
27793,Uzbekistan,2012,female,55-74 years,25,1283060,1.95,Uzbekistan2012,668.0,"51,821,573,338",1964,Boomers
27794,Uzbekistan,2012,female,75+ years,4,338557,1.18,Uzbekistan2012,668.0,"51,821,573,338",1964,Silent
27795,Uzbekistan,2012,female,5-14 years,16,2578408,0.62,Uzbekistan2012,668.0,"51,821,573,338",1964,Generation Z
27796,Uzbekistan,2013,male,35-54 years,481,3346411,14.37,Uzbekistan2013,672.0,"57,690,453,461",2150,Generation X
27797,Uzbekistan,2013,male,25-34 years,328,2644648,12.40,Uzbekistan2013,672.0,"57,690,453,461",2150,Millenials
27798,Uzbekistan,2013,female,15-24 years,323,3039740,10.63,Uzbekistan2013,672.0,"57,690,453,461",2150,Millenials
27799,Uzbekistan,2013,male,15-24 years,320,3171202,10.09,Uzbekistan2013,672.0,"57,690,453,461",2150,Millenials
27800,Uzbekistan,2013,male,55-74 years,119,1202790,9.89,Uzbekistan2013,672.0,"57,690,453,461",2150,Boomers
27801,Uzbekistan,2013,male,75+ years,13,221002,5.88,Uzbekistan2013,672.0,"57,690,453,461",2150,Silent
27802,Uzbekistan,2013,female,25-34 years,146,2647820,5.51,Uzbekistan2013,672.0,"57,690,453,461",2150,Millenials
27803,Uzbekistan,2013,female,35-54 years,99,3547895,2.79,Uzbekistan2013,672.0,"57,690,453,461",2150,Generation X
27804,Uzbekistan,2013,female,75+ years,8,345180,2.32,Uzbekistan2013,672.0,"57,690,453,461",2150,Silent
27805,Uzbekistan,2013,male,5-14 years,61,2720938,2.24,Uzbekistan2013,672.0,"57,690,453,461",2150,Generation Z
27806,Uzbekistan,2013,female,55-74 years,21,1356298,1.55,Uzbekistan2013,672.0,"57,690,453,461",2150,Boomers
27807,Uzbekistan,2013,female,5-14 years,31,2595000,1.19,Uzbekistan2013,672.0,"57,690,453,461",2150,Generation Z
27808,Uzbekistan,2014,male,35-54 years,519,3421300,15.17,Uzbekistan2014,675.0,"63,067,077,179",2309,Generation X
27809,Uzbekistan,2014,male,25-34 years,318,2739150,11.61,Uzbekistan2014,675.0,"63,067,077,179",2309,Millenials
27810,Uzbekistan,2014,female,15-24 years,347,2992817,11.59,Uzbekistan2014,675.0,"63,067,077,179",2309,Millenials
27811,Uzbekistan,2014,male,55-74 years,144,1271111,11.33,Uzbekistan2014,675.0,"63,067,077,179",2309,Boomers
27812,Uzbekistan,2014,male,15-24 years,347,3126905,11.10,Uzbekistan2014,675.0,"63,067,077,179",2309,Millenials
27813,Uzbekistan,2014,male,75+ years,17,224995,7.56,Uzbekistan2014,675.0,"63,067,077,179",2309,Silent
27814,Uzbekistan,2014,female,25-34 years,162,2735238,5.92,Uzbekistan2014,675.0,"63,067,077,179",2309,Millenials
27815,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,Uzbekistan2014,675.0,"63,067,077,179",2309,Generation X
27816,Uzbekistan,2014,female,75+ years,9,348465,2.58,Uzbekistan2014,675.0,"63,067,077,179",2309,Silent
27817,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,Uzbekistan2014,675.0,"63,067,077,179",2309,Generation Z
27818,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,Uzbekistan2014,675.0,"63,067,077,179",2309,Generation Z
27819,Uzbekistan,2014,female,55-74 years,21,1438935,1.46,Uzbekistan2014,675.0,"63,067,077,179",2309,Boomers

In [2]:
#2) Limpiamos la Dataset: empezamos buscando los duplicados.
data_without_duplicates = data.drop_duplicates()
data_without_duplicates.describe

<bound method DataFrame.describe of           country  year     sex          age  suicides_no  population  \
0         Albania  1987    male  15-24 years           21      312900
1         Albania  1987    male  35-54 years           16      308000
2         Albania  1987  female  15-24 years           14      289700
3         Albania  1987    male    75+ years            1       21800
4         Albania  1987    male  25-34 years            9      274300
5         Albania  1987  female    75+ years            1       35600
6         Albania  1987  female  35-54 years            6      278800
7         Albania  1987  female  25-34 years            4      257200
8         Albania  1987    male  55-74 years            1      137500
9         Albania  1987  female   5-14 years            0      311000
10        Albania  1987  female  55-74 years            0      144600
11        Albania  1987    male   5-14 years            0      338200
12        Albania  1988  female    75+ years            2       36400
13        Albania  1988    male  15-24 years           17      319200
14        Albania  1988    male    75+ years            1       22300
15        Albania  1988    male  35-54 years           14      314100
16        Albania  1988    male  55-74 years            4      140200
17        Albania  1988  female  15-24 years            8      295600
18        Albania  1988  female  55-74 years            3      147500
19        Albania  1988  female  25-34 years            5      262400
20        Albania  1988    male  25-34 years            5      279900
21        Albania  1988  female  35-54 years            4      284500
22        Albania  1988  female   5-14 years            0      317200
23        Albania  1988    male   5-14 years            0      345000
24        Albania  1989    male    75+ years            2       22500
25        Albania  1989    male  25-34 years           18      283600
26        Albania  1989    male  35-54 years           15      318400
27        Albania  1989    male  55-74 years            6      142100
28        Albania  1989    male  15-24 years           12      323500
29        Albania  1989  female  35-54 years            7      288600
...           ...   ...     ...          ...          ...         ...
27790  Uzbekistan  2012  female  25-34 years          148     2556673
27791  Uzbekistan  2012  female  35-54 years           89     3474788
27792  Uzbekistan  2012    male   5-14 years           67     2701361
27793  Uzbekistan  2012  female  55-74 years           25     1283060
27794  Uzbekistan  2012  female    75+ years            4      338557
27795  Uzbekistan  2012  female   5-14 years           16     2578408
27796  Uzbekistan  2013    male  35-54 years          481     3346411
27797  Uzbekistan  2013    male  25-34 years          328     2644648
27798  Uzbekistan  2013  female  15-24 years          323     3039740
27799  Uzbekistan  2013    male  15-24 years          320     3171202
27800  Uzbekistan  2013    male  55-74 years          119     1202790
27801  Uzbekistan  2013    male    75+ years           13      221002
27802  Uzbekistan  2013  female  25-34 years          146     2647820
27803  Uzbekistan  2013  female  35-54 years           99     3547895
27804  Uzbekistan  2013  female    75+ years            8      345180
27805  Uzbekistan  2013    male   5-14 years           61     2720938
27806  Uzbekistan  2013  female  55-74 years           21     1356298
27807  Uzbekistan  2013  female   5-14 years           31     2595000
27808  Uzbekistan  2014    male  35-54 years          519     3421300
27809  Uzbekistan  2014    male  25-34 years          318     2739150
27810  Uzbekistan  2014  female  15-24 years          347     2992817
27811  Uzbekistan  2014    male  55-74 years          144     1271111
27812  Uzbekistan  2014    male  15-24 years          347     3126905
27813  Uzbekistan  2014    male    75+ years           17      224995
27814  Uzbekistan  2014  female  25-34 years          162     2735238
27815  Uzbekistan  2014  female  35-54 years          107     3620833
27816  Uzbekistan  2014  female    75+ years            9      348465
27817  Uzbekistan  2014    male   5-14 years           60     2762158
27818  Uzbekistan  2014  female   5-14 years           44     2631600
27819  Uzbekistan  2014  female  55-74 years           21     1438935

       suicides/100k pop    country-year  HDI for year  gdp_for_year ($)   \
0                   6.71     Albania1987           NaN      2,156,624,900
1                   5.19     Albania1987           NaN      2,156,624,900
2                   4.83     Albania1987           NaN      2,156,624,900
3                   4.59     Albania1987           NaN      2,156,624,900
4                   3.28     Albania1987           NaN      2,156,624,900
5                   2.81     Albania1987           NaN      2,156,624,900
6                   2.15     Albania1987           NaN      2,156,624,900
7                   1.56     Albania1987           NaN      2,156,624,900
8                   0.73     Albania1987           NaN      2,156,624,900
9                   0.00     Albania1987           NaN      2,156,624,900
10                  0.00     Albania1987           NaN      2,156,624,900
11                  0.00     Albania1987           NaN      2,156,624,900
12                  5.49     Albania1988           NaN      2,126,000,000
13                  5.33     Albania1988           NaN      2,126,000,000
14                  4.48     Albania1988           NaN      2,126,000,000
15                  4.46     Albania1988           NaN      2,126,000,000
16                  2.85     Albania1988           NaN      2,126,000,000
17                  2.71     Albania1988           NaN      2,126,000,000
18                  2.03     Albania1988           NaN      2,126,000,000
19                  1.91     Albania1988           NaN      2,126,000,000
20                  1.79     Albania1988           NaN      2,126,000,000
21                  1.41     Albania1988           NaN      2,126,000,000
22                  0.00     Albania1988           NaN      2,126,000,000
23                  0.00     Albania1988           NaN      2,126,000,000
24                  8.89     Albania1989           NaN      2,335,124,988
25                  6.35     Albania1989           NaN      2,335,124,988
26                  4.71     Albania1989           NaN      2,335,124,988
27                  4.22     Albania1989           NaN      2,335,124,988
28                  3.71     Albania1989           NaN      2,335,124,988
29                  2.43     Albania1989           NaN      2,335,124,988
...                  ...             ...           ...                ...
27790               5.79  Uzbekistan2012         668.0     51,821,573,338
27791               2.56  Uzbekistan2012         668.0     51,821,573,338
27792               2.48  Uzbekistan2012         668.0     51,821,573,338
27793               1.95  Uzbekistan2012         668.0     51,821,573,338
27794               1.18  Uzbekistan2012         668.0     51,821,573,338
27795               0.62  Uzbekistan2012         668.0     51,821,573,338
27796              14.37  Uzbekistan2013         672.0     57,690,453,461
27797              12.40  Uzbekistan2013         672.0     57,690,453,461
27798              10.63  Uzbekistan2013         672.0     57,690,453,461
27799              10.09  Uzbekistan2013         672.0     57,690,453,461
27800               9.89  Uzbekistan2013         672.0     57,690,453,461
27801               5.88  Uzbekistan2013         672.0     57,690,453,461
27802               5.51  Uzbekistan2013         672.0     57,690,453,461
27803               2.79  Uzbekistan2013         672.0     57,690,453,461
27804               2.32  Uzbekistan2013         672.0     57,690,453,461
27805               2.24  Uzbekistan2013         672.0     57,690,453,461
27806               1.55  Uzbekistan2013         672.0     57,690,453,461
27807               1.19  Uzbekistan2013         672.0     57,690,453,461
27808              15.17  Uzbekistan2014         675.0     63,067,077,179
27809              11.61  Uzbekistan2014         675.0     63,067,077,179
27810              11.59  Uzbekistan2014         675.0     63,067,077,179
27811              11.33  Uzbekistan2014         675.0     63,067,077,179
27812              11.10  Uzbekistan2014         675.0     63,067,077,179
27813               7.56  Uzbekistan2014         675.0     63,067,077,179
27814               5.92  Uzbekistan2014         675.0     63,067,077,179
27815               2.96  Uzbekistan2014         675.0     63,067,077,179
27816               2.58  Uzbekistan2014         675.0     63,067,077,179
27817               2.17  Uzbekistan2014         675.0     63,067,077,179
27818               1.67  Uzbekistan2014         675.0     63,067,077,179
27819               1.46  Uzbekistan2014         675.0     63,067,077,179

       gdp_per_capita ($)       generation
0                     796     Generation X
1                     796           Silent
2                     796     Generation X
3                     796  G.I. Generation
4                     796          Boomers
5                     796  G.I. Generation
6                     796           Silent
7                     796          Boomers
8                     796  G.I. Generation
9                     796     Generation X
10                    796  G.I. Generation
11                    796     Generation X
12                    769  G.I. Generation
13                    769     Generation X
14                    769  G.I. Generation
15                    769           Silent
16                    769  G.I. Generation
17                    769     Generation X
18                    769  G.I. Generation
19                    769          Boomers
20                    769          Boomers
21                    769           Silent
22                    769     Generation X
23                    769     Generation X
24                    833  G.I. Generation
25                    833          Boomers
26                    833           Silent
27                    833  G.I. Generation
28                    833     Generation X
29                    833           Silent
...                   ...              ...
27790                1964       Millenials
27791                1964     Generation X
27792                1964     Generation Z
27793                1964          Boomers
27794                1964           Silent
27795                1964     Generation Z
27796                2150     Generation X
27797                2150       Millenials
27798                2150       Millenials
27799                2150       Millenials
27800                2150          Boomers
27801                2150           Silent
27802                2150       Millenials
27803                2150     Generation X
27804                2150           Silent
27805                2150     Generation Z
27806                2150          Boomers
27807                2150     Generation Z
27808                2309     Generation X
27809                2309       Millenials
27810                2309       Millenials
27811                2309          Boomers
27812                2309       Millenials
27813                2309           Silent
27814                2309       Millenials
27815                2309     Generation X
27816                2309           Silent
27817                2309     Generation Z
27818                2309     Generation Z
27819                2309          Boomers

[27820 rows x 12 columns]>

In [3]:
#eliminamos la columna "HDI for year", ya que tiene mas de 19000 registros nulos:
null_cols=data_without_duplicates.isnull().sum()
null_cols

country                   0
year                      0
sex                       0
age                       0
suicides_no               0
population                0
suicides/100k pop         0
country-year              0
HDI for year          19456
 gdp_for_year ($)         0
gdp_per_capita ($)        0
generation                0
dtype: int64

In [5]:
data_without_duplicates=data_without_duplicates.drop(['HDI for year'], axis=0)
print(data_without_duplicates)

KeyError: "['HDI for year'] not found in axis"

In [6]:
data_without_duplicates.columns

Index([u'country', u'year', u'sex', u'age', u'suicides_no', u'population',
       u'suicides/100k pop', u'country-year', u'HDI for year',
       u' gdp_for_year ($) ', u'gdp_per_capita ($)', u'generation'],
      dtype='object')

In [7]:
#eliminamos la columna 'country-year' porque tenemos ya otras 2 columnas que nos facilitan esos datos:
data_without_duplicates=data_without_duplicates.drop(['country-year'], axis=1)

In [8]:
data_without_duplicates.columns

Index([u'country', u'year', u'sex', u'age', u'suicides_no', u'population',
       u'suicides/100k pop', u'HDI for year', u' gdp_for_year ($) ',
       u'gdp_per_capita ($)', u'generation'],
      dtype='object')

In [10]:
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.cbook as cbk

ImportError: cannot import name cbook

In [11]:
#calculamos el numero de suicidios en funcion del sexo (en porcentaje)
Suicides_per_sex= data_without_duplicates.groupby(['sex'])['suicides/100k pop'].sum()/(75014.77+281529.06)*100
Suicides_per_sex

sex
female    21.039425
male      78.960575
Name: suicides/100k pop, dtype: float64

In [12]:
#calculamos suicidios por pais:
Suicides_per_country= data_without_duplicates.groupby(['country'])['suicides/100k pop'].sum()
Suicides_per_country_ordered = Suicides_per_country.sort_values(ascending=False)
Suicides_per_country_ordered.head(5)

country
Russian Federation    11305.13
Lithuania             10588.88
Hungary               10156.07
Kazakhstan             9519.52
Republic of Korea      9350.45
Name: suicides/100k pop, dtype: float64

In [13]:
Suicides_per_year= data_without_duplicates.groupby(['year','country'])['suicides/100k pop'].sum()
Suicides_per_year.head(10)

year  country
1985  Antigua and Barbuda      0.00
      Argentina              134.47
      Australia              163.41
      Austria                384.81
      Bahamas                  4.76
      Bahrain                 20.12
      Barbados                61.72
      Belgium                332.04
      Brazil                  59.18
      Bulgaria               303.12
Name: suicides/100k pop, dtype: float64

In [14]:
#Pivotamos la columna año, para conseguir una tabla de la evolucion del numero de casos de suicidio registrados entre 1985 y 2016 por pais:
suicides_per_year_country_pivot=data_without_duplicates.pivot_table(index='country', columns='year', values='suicides/100k pop')
suicides_per_year_country_pivot.fillna(0)

year,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
country,,,,,,,,,,,,,,,,,,,,,
Albania,0.000000,0.000000,2.654167,2.705000,2.783333,0.000000,0.000000,1.500000,2.713333,2.681667,...,5.487500,5.920833,0.000000,3.471667,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
Antigua and Barbuda,0.000000,0.000000,0.000000,0.000000,0.000000,1.436667,0.000000,0.000000,1.250000,0.000000,...,0.665000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.301667,0.000
Argentina,11.205833,12.741667,12.081667,12.186667,11.577500,11.241667,9.936667,10.571667,11.230833,10.170833,...,9.862500,9.842500,8.943333,9.270000,8.822500,9.985000,8.618333,9.279167,9.344167,0.000
Armenia,0.000000,0.000000,0.000000,0.000000,0.000000,3.426667,3.822500,3.405000,4.254167,5.560833,...,3.251667,2.929167,2.808333,3.367500,2.748333,3.047500,3.123333,3.084167,3.773333,4.056
Aruba,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,7.682500,3.453333,3.519167,4.887500,7.785000,0.000000,0.000000,0.000000,0.000000,0.000
Australia,13.617500,14.649167,15.735000,14.943333,14.009167,14.362500,15.012500,14.220000,12.912500,13.979167,...,10.854167,10.874167,10.843333,11.053333,11.101667,11.630833,11.565000,12.422500,12.848333,0.000
Austria,32.067500,33.483333,33.823333,29.803333,29.943333,29.481667,29.622500,28.478333,28.996667,28.635000,...,18.109167,18.037500,17.768333,17.295833,17.624167,17.219167,17.676667,17.485000,16.218333,18.323
Azerbaijan,0.000000,0.000000,0.000000,0.000000,0.000000,2.050833,2.685833,2.898333,2.626667,1.003333,...,0.985833,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
Bahamas,0.396667,0.000000,1.132500,0.000000,0.000000,0.000000,0.000000,0.000000,3.125833,0.883333,...,1.118333,1.040833,1.331667,4.860000,1.082500,0.986667,1.159167,0.000000,0.000000,0.000
Bahrain,1.676667,0.000000,2.140000,2.066667,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.674167,2.324167,2.049167,0.990833,1.246667,0.723333,0.207500,0.543333,0.000000,0.000
Barbados,5.143333,3.060833,2.455000,4.782500,6.131667,10.102500,6.410833,5.294167,7.577500,5.590000,...,0.000000,0.192500,2.400000,0.635000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
Belarus,0.000000,0.000000,0.000000,0.000000,0.000000,22.864167,24.803333,26.186667,30.425833,33.631667,...,29.657500,29.346667,31.295000,27.665000,24.946667,0.000000,22.776667,21.075833,0.000000,0.000
Belgium,27.670000,26.224167,27.313333,23.650000,23.737500,23.092500,22.001667,22.156667,25.039167,25.033333,...,17.380833,18.461667,18.195833,18.348333,18.892500,18.094167,16.795833,16.820833,16.388333,0.000
Belize,0.000000,1.614167,2.617500,0.000000,0.430000,2.475000,1.994167,0.000000,0.540833,13.727500,...,6.540833,7.196667,4.813333,5.123333,12.775000,6.120833,4.700000,7.579167,11.288333,0.000
Bosnia and Herzegovina,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.109167,0.000000,0.000000,9.125000,0.000000,0.000
Brazil,4.931667,4.763333,5.843333,5.446667,5.335000,5.588333,5.695000,5.410000,5.655000,5.959167,...,5.973333,6.017500,5.864167,6.060833,6.034167,6.204167,6.117500,6.094167,6.454167,0.000
Bulgaria,25.260000,22.956667,25.700000,24.374167,24.349167,21.369167,22.411667,25.883333,23.196667,24.032500,...,14.480833,14.195000,12.868333,13.187500,11.126667,13.680833,11.180000,11.647500,0.000000,0.000
Cabo Verde,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,11.153333,0.000000,0.000000,0.000000,0.000000,0.000
Canada,13.871667,15.842500,14.944167,14.615000,14.248333,13.751667,13.981667,13.633333,13.668333,13.492500,...,10.620833,10.632500,10.889167,11.055833,10.418333,10.656667,11.090833,0.000000,0.000000,0.000
Chile,9.075833,7.578333,7.451667,7.908333,8.370000,7.655000,8.235833,6.573333,8.598333,7.945000,...,12.576667,13.990000,14.525000,13.573333,13.403333,12.367500,11.210000,11.447500,12.306667,0.000
Colombia,5.213333,4.175833,3.764167,4.220000,3.474167,3.619167,3.630833,4.123333,4.102500,4.662500,...,6.187500,6.185000,6.152500,5.603333,5.240000,5.537500,5.294167,5.551667,5.866667,0.000
Costa Rica,5.788333,7.486667,7.130000,7.415000,7.064167,7.772500,5.143333,6.045000,8.235833,6.732500,...,6.279167,6.022500,6.447500,7.029167,7.485833,6.730000,7.438333,5.904167,0.000000,0.000
Croatia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,20.287500,22.140833,21.190833,20.164167,18.425833,19.917500,17.525000,18.503333,19.140000,21.356
Cuba,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,30.809167,32.744167,30.275833,...,15.681667,15.915833,16.777500,16.844167,17.254167,17.000000,15.871667,15.385833,16.192500,0.000
Cyprus,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,3.014167,4.922500,4.627500,4.906667,3.648333,3.575000,5.384167,4.758333,4.132500,4.715
Czech Republic,0.000000,0.000000,0.000000,0.000000,0.000000,26.185000,24.334167,25.267500,24.803333,24.440000,...,14.231667,14.584167,14.975833,14.635000,15.520000,16.352500,15.505833,14.607500,14.239167,16.176
Denmark,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,21.101667,...,11.663333,11.920833,12.058333,10.835000,10.527500,11.934167,11.212500,11.477500,10.118333,0.000
Dominica,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
Ecuador,6.876667,6.378333,5.210833,6.274167,5.865000,5.040000,5.580000,6.316667,5.909167,5.639167,...,7.997500,7.940833,7.854167,6.790833,6.816667,7.073333,5.240000,5.501667,8.115833,0.000
El Salvador,0.000000,0.000000,0.000000,0.000000,0.000000,15.371667,14.275000,10.051667,10.307500,0.000000,...,10.595000,10.485000,10.343333,8.160000,9.621667,10.261667,9.671667,8.486667,0.000000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Puerto Rico,12.884167,14.852500,11.980000,13.474167,14.128333,15.131667,15.400833,11.275833,12.604167,12.273333,...,7.756667,8.923333,10.408333,8.653333,7.545833,7.258333,7.549167,6.424167,7.131667,0.000
Qatar,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.384167,1.129167,1.658333,1.069167,1.570833,1.105833,0.685833,1.582500,1.570000,1.643
Republic of Korea,12.220833,11.942500,10.686667,9.548333,10.116667,10.044167,9.681667,10.615833,13.290000,13.783333,...,38.878333,37.690000,43.293333,43.183333,42.920833,36.938333,35.714167,32.110833,32.428333,0.000
Romania,0.000000,0.000000,0.000000,0.000000,13.147500,10.493333,11.115000,13.681667,13.505833,14.398333,...,11.338333,11.700000,12.001667,12.503333,11.565000,11.835833,11.499167,10.919167,11.129167,11.633
Russian Federation,0.000000,0.000000,0.000000,0.000000,33.235000,33.264167,33.033333,36.456667,43.505000,47.303333,...,32.249167,30.566667,29.400000,26.600833,24.973333,23.792500,22.830833,21.601667,19.743333,0.000
Saint Kitts and Nevis,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
Saint Lucia,0.000000,4.995833,11.785000,15.184167,7.409167,2.243333,8.674167,8.175833,6.273333,3.816667,...,0.000000,0.000000,6.860000,2.525833,4.443333,7.085833,9.508333,7.630000,0.000000,0.000
Saint Vincent and Grenadines,2.732500,0.000000,0.000000,0.000000,0.000000,6.005000,0.000000,0.000000,0.000000,0.000000,...,8.532500,3.357500,0.931667,4.569167,3.915000,8.107500,0.000000,6.731667,2.340000,0.000
San Marino,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
Serbia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,21.537500,20.217500,21.535833,19.540000,20.287500,19.544167,18.144167,18.065000,17.164167,0.000
Seychelles,13.015000,1.938333,5.060000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,12.303333,3.255833,3.650833,4.332500,4.278333,2.791667,10.950000,3.610833,6.770833,0.000
Singapore,29.446667,27.050833,22.796667,30.015833,29.509167,22.669167,19.115000,17.118333,19.595000,20.570833,...,13.813333,12.520833,12.465000,10.769167,9.746667,11.801667,11.489167,10.981667,9.107500,0.000
Slovakia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,17.852500,16.278333,15.420000,...,0.000000,11.183333,11.590000,11.973333,0.000000,10.790000,11.992500,11.068333,0.000000,0.000
Slovenia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,24.287500,21.924167,22.392500,22.132500,23.471667,23.311667,23.585000,20.030833,22.067500,0.000
South Africa,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.010000,1.178333,0.892500,1.090833,0.775833,1.130000,1.241667,1.256667,1.083333,0.000
Spain,9.577500,9.985833,10.178333,10.606667,10.540833,10.770000,10.153333,9.917500,10.070833,10.360000,...,8.245833,8.210000,8.168333,7.286667,7.382500,8.073333,8.443333,8.695833,8.115000,0.000
Sri Lanka,46.560000,44.150000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
Suriname,39.236667,17.665833,20.975000,17.476667,17.676667,17.840833,17.955000,11.496667,0.000000,0.000000,...,29.678333,34.735000,30.809167,35.441667,29.442500,37.842500,23.900000,29.778333,0.000000,0.000
Sweden,0.000000,0.000000,19.242500,19.305833,19.861667,18.504167,18.128333,16.731667,16.747500,16.307500,...,12.282500,12.973333,13.366667,12.211667,11.814167,12.342500,13.183333,12.420833,12.441667,13.884
Switzerland,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,21.317500,19.792500,15.010833,13.376667,14.018333,13.782500,14.188333,13.508333,13.721667,0.000
Thailand,6.878333,5.992500,6.818333,0.000000,0.000000,7.993333,7.205000,6.925000,0.000000,4.689167,...,6.595000,6.515000,6.546667,6.708333,6.465833,6.724167,6.630000,6.413333,6.762500,7.732
Trinidad and Tobago,2.514167,10.260833,12.961667,19.062500,16.513333,15.531667,12.795000,16.199167,13.460833,13.283333,...,11.965000,14.854167,10.020000,12.541667,11.557500,0.000000,0.000000,0.000000,0.000000,0.000
Turkey,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.774167,2.640833,1.922500,2.366667,2.951667,2.569167,2.372500,0.000
Turkmenistan,0.000000,0.000000,14.467500,13.537500,11.277500,14.334167,10.578333,9.320833,9.619167,9.743333,...,8.057500,9.798333,3.545000,3.812500,2.635833,2.550000,1.940833,2.345833,2.373333,0.000
Ukraine,0.000000,0.000000,24.503333,23.893333,26.360000,24.725000,24.825833,26.874167,29.342500,32.024167,...,23.426667,22.875000,23.271667,21.922500,22.000000,22.372500,0.000000,20.875000,20.393333,0.000
United Arab Emirates,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.332500,0.988333,0.977500,1.892500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
United Kingdom,9.704167,9.334167,8.650833,9.545833,8.265833,8.611667,8.233333,8.229167,8.070833,7.896667,...,6.243333,6.725833,6.500000,6.450833,6.524167,6.622500,7.076667,6.994167,7.228333,0.000
United States,15.393333,15.970833,15.971667,15.642500,15.203333,15.650000,15.314167,14.814167,14.926667,14.669167,...,12.426667,12.770000,12.849167,13.240833,13.530000,13.761667,13.889167,14.277500,14.617500,0.000
Uruguay,14.884167,14.372500,13.702500,13.705000,16.371667,15.055833,0.000000,0.000000,18.585000,17.833333,...,22.192500,19.544167,19.812500,21.452500,0.000000,22.029167,20.757500,20.720000,22.501667,0.000
Uzbekistan,0.000000,0.000000,0.000000,0.000000,0.000000,10.780000,10.348333,9.274167,9.313333,9.237500,...,0.000000,0.000000,5.071667,5.269167,5.595000,6.460833,6.571667,7.093333,0.000000,0.000